// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdaKTlMTgxAI0GXLbT4aPPQWZkTkmNRc',
    appId: '1:489773301323:web:80bf1cf64836e82b1897ce',
    messagingSenderId: '489773301323',
    projectId: 'unibeethree',
    authDomain: 'unibeethree.firebaseapp.com',
    storageBucket: 'unibeethree.appspot.com',
    measurementId: 'G-4B49KW963K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-kNCm4dBZ-6hcgz5CUji1boBbhIqtNw',
    appId: '1:489773301323:android:efc862b49983217d1897ce',
    messagingSenderId: '489773301323',
    projectId: 'unibeethree',
    storageBucket: 'unibeethree.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpqZvAxyFOcrj532Op-YMNVx1GvVobhc',
    appId: '1:489773301323:ios:8e18493a0ab778951897ce',
    messagingSenderId: '489773301323',
    projectId: 'unibeethree',
    storageBucket: 'unibeethree.appspot.com',
    iosClientId:
        '489773301323-pqes17go953rdq678m5qgr54v1fverhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.unibeethree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpqZvAxyFOcrj532Op-YMNVx1GvVobhc',
    appId: '1:489773301323:ios:8e18493a0ab778951897ce',
    messagingSenderId: '489773301323',
    projectId: 'unibeethree',
    storageBucket: 'unibeethree.appspot.com',
    iosClientId:
        '489773301323-pqes17go953rdq678m5qgr54v1fverhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.unibeethree',
  );
}
